FROM  python:3.7.16-slim-bullseye
##ENV mongo_dg_username=admin\
##    mongo_db_pass=pasword
RUN apt update -y && apt install vim -y && apt install net-tools -y && apt install openssh-server -y

#COPY . /dropbox
#RUN pip3 install gunicorn flask wheel requests
#CMD python3 /dropbox/myflask.py
#CMD python3 gunicorn --bind 0.0.0.0:5000 wsgi.app

#WORKDIR /dockerlesson will cd to /dockerlesson inside container
##RUN pip3 install -r requirements.txt #it will only run inside docker container
#CMD python3 server2.py
## COPY dest-on-host dest-on-container
## CMD["fist part of command","s part of ..","third pa.."] it will be inside container

